# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-03 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wild', '0002_auto_20160903_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='cost',
        ),
        migrations.AddField(
            model_name='user',
            name='i_am',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='life_style',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
